language: java

sudo: required

services:
  - docker

cache: pip

before_install:
  - docker pull dainco/algobox-base-java
  - docker pull dainco/algobox-base-jupyter

script:
  - cd java/algobox
    gradle algobox-api:clean algobox-api:test algobox-api:shadowJar
    docker build -t dainco/algobox-api ./algobox-api
    gradle algobox-datacollector:clean algobox-datacollector:test algobox-datacollector:shadowJar
    docker build -t dainco/algobox-datacollector ./algobox-datacollector
    cd ../../python/algobox
    docker build -t dainco/algobox-jupyter .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag dainco/algobox-api docker.io/dainco/algobox-api:latest;
    docker push docker.io/dainco/algobox-api:latest;

    docker tag dainco/algobox-datacollector docker.io/dainco/algobox-datacollector:latest;
    docker push docker.io/dainco/algobox-datacollector:latest;

    docker tag dainco/algobox-jupyter docker.io/dainco/algobox-jupyter:latest;
    docker push docker.io/dainco/algobox-jupyter:latest;
    fi

