language: java

sudo: required

services:
  - docker

cache: pip

install:
  - docker build -t dainco/algobox-base-java:latest ./docker/algobox-base-java
  - docker build -t dainco/algobox-base-jupyter:latest ./docker/algobox-base-jupyter

script:
  - cd java

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dainco/algobox-base-java:latest;
    docker push dainco/algobox-base-jupyter:latest;
    fi

