language: java

sudo: required

services:
  - docker

cache: pip

script:
  - bundle exec build-algobox-jupyter.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push dainco/algobox-jupyter;
    fi

