sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t dainco/algobox-jupyter ./python/algobox

script:
  - bundle exec gradle algobox-api:clean algobox-api:test algobox-api:shadowJar chdir=./java/algobox

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push dainco/algobox-jupyter;
    fi

