language: java

sudo: required

services:
  - docker

cache: pip

script:
  - docker build -t dainco/algobox-jupyter ./python/algobox
  - cd java/algobox
  - gradle algobox-api:clean algobox-api:test algobox-api:shadowJar

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dainco/algobox-jupyter;
    fi

