version: '2'

services:
  mongo:
    image: mongo:3.4
    networks: 
      - algobox

  algobox-api:
    image: dainco/algobox-api
    depends_on:
      - mongo
    environment:
      - application.enableSwagger=true
      - application.port=8080
      - application.apiUrl=https://algobox-gateway
      - application.strategiesJarPath=/opt/strategies
      - market.marketOpenTimeUtc=22:30
      - market.marketCloseTimeUtc=22:00
      - mongo.connectionUrl=mongodb://mongo:27017
      - mongo.database=datamaster
    volumes:
      - /opt/strategies:/opt/strategies
    networks:
      - algobox

  algobox-datacollector:
    image: dainco/algobox-datacollector
    depends_on:
      - mongo
    environment:
      - application.enableSwagger=true
      - application.port=8080
      - application.apiUrl=https://algobox-gateway/datacollector
      - market.marketOpenTimeUtc=22:30
      - market.marketCloseTimeUtc=22:00
      - mongo.connectionUrl=mongodb://mongo:27017
      - mongo.database=datacollector
    networks:
      - algobox

  algobox-jupyter:
    image: dainco/algobox-jupyter
    depends_on:
      - algobox-api
      - algobox-datacollector
    networks:
      - algobox

  algobox-gateway:
    build: ./docker/algobox-gateway
    depends_on:
      - algobox-api
      - algobox-datacollector
      - algobox-jupyter
    ports:
      - 80:80
      - 443:443
    networks:
      - algobox

networks:
  algobox:

